<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTunerchipTunesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("tunerchip_tunes");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("tunerchip_tunes", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("tune_id", $columns) && $table->integer("tune_id")->autoIncrement();
			!in_array("character_id", $columns) && $table->integer("character_id")->nullable();
			!in_array("name", $columns) && $table->string("name", 255)->nullable();
			!in_array("model_name", $columns) && $table->string("model_name", 255)->nullable();
			!in_array("offsets", $columns) && $table->longText("offsets")->nullable();
			!in_array("timestamp", $columns) && $table->integer("timestamp")->nullable();

			!in_array("tune_id", $indexes) && $table->index("tune_id");
			!in_array("character_id", $indexes) && $table->index("character_id");
			!in_array("name", $indexes) && $table->index("name");
			!in_array("model_name", $indexes) && $table->index("model_name");
			!in_array("timestamp", $indexes) && $table->index("timestamp");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("tunerchip_tunes");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `tunerchip_tunes`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `tunerchip_tunes` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}