<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateGcphoneMessagesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("gcphone_messages");

		$func = Schema::hasTable("gcphone_messages") ? "table" : "create";

		Schema::$func("gcphone_messages", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("transmitter", $columns) && $table->string("transmitter", 255)->nullable();
			!in_array("receiver", $columns) && $table->string("receiver", 255)->nullable();
			!in_array("message", $columns) && $table->longText("message")->nullable()->default("'0'");
			!in_array("time", $columns) && $table->timestamp("time")->default("current_timestamp()");
			!in_array("isRead", $columns) && $table->integer("isRead")->nullable()->default("0");
			!in_array("owner", $columns) && $table->integer("owner")->nullable()->default("0");

			!in_array("receiver", $indexes) && $table->index("receiver");
			!in_array("transmitter", $indexes) && $table->index("transmitter");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("gcphone_messages");
	}

	/**
	 * Collect all columns that are indexed in the gcphone_messages table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("gcphone_messages")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("gcphone_messages");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}