<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateMdtReportsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("mdt_reports");

		$func = Schema::hasTable("mdt_reports") ? "table" : "create";

		Schema::$func("mdt_reports", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("report_id", $columns) && $table->integer("report_id")->autoIncrement();
			!in_array("creator_cid", $columns) && $table->integer("creator_cid");
			!in_array("editor_cid", $columns) && $table->integer("editor_cid");
			!in_array("title", $columns) && $table->longText("title")->nullable();
			!in_array("body", $columns) && $table->longText("body")->nullable();
			!in_array("created_at", $columns) && $table->integer("created_at")->nullable()->default("0");
			!in_array("modified_at", $columns) && $table->integer("modified_at")->nullable()->default("0");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("mdt_reports");
	}

	/**
	 * Collect all columns that are indexed in the mdt_reports table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("mdt_reports")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("mdt_reports");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}