<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateOutfitsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("outfits");

		$func = Schema::hasTable("outfits") ? "table" : "create";

		Schema::$func("outfits", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("cid", $columns) && $table->integer("cid")->nullable();
			!in_array("name", $columns) && $table->longText("name")->nullable();
			!in_array("data", $columns) && $table->longText("data")->nullable();
			!in_array("ped_data", $columns) && $table->longText("ped_data")->nullable();
			!in_array("updated_at", $columns) && $table->integer("updated_at")->nullable();

			!in_array("cid", $indexes) && $table->index("cid");
			!in_array("name", $indexes) && $table->index("name");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("outfits");
	}

	/**
	 * Collect all columns that are indexed in the outfits table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("outfits")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("outfits");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}