<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateErrorsDatabaseTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("errors_database");

		$func = Schema::hasTable("errors_database") ? "table" : "create";

		Schema::$func("errors_database", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("error_id", $columns) && $table->integer("error_id")->autoIncrement();
			!in_array("error_code", $columns) && $table->longText("error_code")->nullable();
			!in_array("error_message", $columns) && $table->longText("error_message")->nullable();
			!in_array("error_query", $columns) && $table->longText("error_query")->nullable();
			!in_array("error_number", $columns) && $table->integer("error_number")->nullable();
			!in_array("server_id", $columns) && $table->integer("server_id")->nullable();
			!in_array("timestamp", $columns) && $table->integer("timestamp")->nullable();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("errors_database");
	}

	/**
	 * Collect all columns that are indexed in the errors_database table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("errors_database")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("errors_database");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}