<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateMoneyLogsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("money_logs");

		$func = Schema::hasTable("money_logs") ? "table" : "create";

		Schema::$func("money_logs", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("type", $columns) && $table->string("type", 50);
			!in_array("license_identifier", $columns) && $table->string("license_identifier", 50);
			!in_array("character_id", $columns) && $table->integer("character_id");
			!in_array("amount", $columns) && $table->integer("amount");
			!in_array("balance_after", $columns) && $table->integer("balance_after");
			!in_array("details", $columns) && $table->longText("details")->nullable();
			!in_array("timestamp", $columns) && $table->timestamp("timestamp")->default("current_timestamp()");

			!in_array("license_identifier", $indexes) && $table->index("license_identifier");
			!in_array("character_id", $indexes) && $table->index("character_id");
			!in_array("type", $indexes) && $table->index("type");
			!in_array("timestamp", $indexes) && $table->index("timestamp");
			!in_array("details", $indexes) && $table->index("details");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("money_logs");
	}

	/**
	 * Collect all columns that are indexed in the money_logs table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("money_logs")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("money_logs");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}