<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFurnitureTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("furniture");

		$func = Schema::hasTable("furniture") ? "table" : "create";

		Schema::$func("furniture", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("property_id", $columns) && $table->integer("property_id")->nullable();
			!in_array("hash", $columns) && $table->bigInteger("hash")->nullable();
			!in_array("coords", $columns) && $table->longText("coords")->nullable();
			!in_array("storage_id", $columns) && $table->integer("storage_id")->nullable();
			!in_array("storage_size", $columns) && $table->integer("storage_size")->nullable();
			!in_array("weed_growth", $columns) && $table->integer("weed_growth")->nullable();
			!in_array("weed_timestamp", $columns) && $table->integer("weed_timestamp")->nullable();

			!in_array("property_id", $indexes) && $table->index("property_id");
			!in_array("weed_timestamp", $indexes) && $table->index("weed_timestamp");
			!in_array("id", $indexes) && $table->index("id");
			!in_array("storage_id", $indexes) && $table->index("storage_id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("furniture");
	}

	/**
	 * Collect all columns that are indexed in the furniture table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("furniture")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("furniture");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}