<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateErrorsClientTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("errors_client");

		$func = Schema::hasTable("errors_client") ? "table" : "create";

		Schema::$func("errors_client", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("error_id", $columns) && $table->integer("error_id")->autoIncrement();
			!in_array("license_identifier", $columns) && $table->string("license_identifier", 50)->nullable();
			!in_array("error_location", $columns) && $table->longText("error_location")->nullable();
			!in_array("error_trace", $columns) && $table->longText("error_trace")->nullable();
			!in_array("full_trace", $columns) && $table->longText("full_trace")->nullable();
			!in_array("error_feedback", $columns) && $table->longText("error_feedback")->nullable();
			!in_array("player_ping", $columns) && $table->integer("player_ping")->nullable();
			!in_array("server_id", $columns) && $table->integer("server_id")->nullable();
			!in_array("server_version", $columns) && $table->string("server_version", 50)->nullable();
			!in_array("timestamp", $columns) && $table->integer("timestamp")->nullable();

			!in_array("license_identifier", $indexes) && $table->index("license_identifier");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("errors_client");
	}

	/**
	 * Collect all columns that are indexed in the errors_client table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("errors_client")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("errors_client");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}