<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDailyActivitiesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("daily_activities");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("daily_activities", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("license_identifier", $columns) && $table->string("license_identifier", 50)->nullable();
			!in_array("tasks_identifier", $columns) && $table->string("tasks_identifier", 50)->nullable();
			!in_array("task_id", $columns) && $table->integer("task_id")->nullable();
			!in_array("task_name", $columns) && $table->string("task_name", 50)->nullable();
			!in_array("task_icon", $columns) && $table->string("task_icon", 50)->nullable();
			!in_array("task_data", $columns) && $table->longText("task_data")->nullable();
			!in_array("task_locked", $columns) && $table->tinyInteger("task_locked")->nullable()->default("0");
			!in_array("task_completed", $columns) && $table->tinyInteger("task_completed")->nullable()->default("0");
			!in_array("task_claimed", $columns) && $table->tinyInteger("task_claimed")->nullable()->default("0");

			!in_array("license_identifier", $indexes) && $table->index("license_identifier");
			!in_array("tasks_identifier", $indexes) && $table->index("tasks_identifier");
			!in_array("task_id", $indexes) && $table->index("task_id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("daily_activities");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `daily_activities`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `daily_activities` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}