<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateResidencesMotelsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("residences_motels");

		$func = Schema::hasTable("residences_motels") ? "table" : "create";

		Schema::$func("residences_motels", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("motel", $columns) && $table->longText("motel")->nullable();
			!in_array("room_id", $columns) && $table->integer("room_id")->nullable();
			!in_array("cid", $columns) && $table->integer("cid")->nullable();
			!in_array("expire", $columns) && $table->integer("expire")->nullable();

			!in_array("cid", $indexes) && $table->index("cid");
			!in_array("motel", $indexes) && $table->index("motel");
			!in_array("room_id", $indexes) && $table->index("room_id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("residences_motels");
	}

	/**
	 * Collect all columns that are indexed in the residences_motels table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("residences_motels")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("residences_motels");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}