<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUserLogsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("user_logs");

		$func = Schema::hasTable("user_logs") ? "table" : "create";

		Schema::$func("user_logs", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("identifier", $columns) && $table->string("identifier", 50)->nullable();
			!in_array("action", $columns) && $table->string("action", 50)->nullable();
			!in_array("details", $columns) && $table->longText("details")->nullable();
			!in_array("metadata", $columns) && $table->longText("metadata")->nullable();
			!in_array("timestamp", $columns) && $table->timestamp("timestamp")->default("current_timestamp()");

			!in_array("identifier", $indexes) && $table->index("identifier");
			!in_array("action", $indexes) && $table->index("action");
			!in_array("details", $indexes) && $table->index("details");
			!in_array("metadata", $indexes) && $table->index("metadata");
			!in_array("timestamp", $indexes) && $table->index("timestamp");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("user_logs");
	}

	/**
	 * Collect all columns that are indexed in the user_logs table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("user_logs")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("user_logs");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}