<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFinancesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("finances");

		$func = Schema::hasTable("finances") ? "table" : "create";

		Schema::$func("finances", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("cid", $columns) && $table->integer("cid")->nullable();
			!in_array("amount", $columns) && $table->integer("amount")->nullable();
			!in_array("completed", $columns) && $table->integer("completed")->nullable()->default("0");
			!in_array("timestamp", $columns) && $table->timestamp("timestamp")->default("current_timestamp()");
			!in_array("description", $columns) && $table->longText("description")->nullable();

			!in_array("cid", $indexes) && $table->index("cid");
			!in_array("description", $indexes) && $table->index("description");
			!in_array("id", $indexes) && $table->index("id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("finances");
	}

	/**
	 * Collect all columns that are indexed in the finances table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("finances")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("finances");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}