<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateUserStatisticsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("user_statistics");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("user_statistics", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("date", $columns) && $table->string("date", 50)->primary();
			!in_array("total_joins", $columns) && $table->integer("total_joins")->nullable()->default("0");
			!in_array("max_joined", $columns) && $table->integer("max_joined")->nullable()->default("0");
			!in_array("joined_users", $columns) && $table->longText("joined_users")->nullable();
			!in_array("max_queue", $columns) && $table->integer("max_queue")->nullable()->default("0");
			!in_array("playtime", $columns) && $table->integer("playtime")->nullable()->default("0");
			!in_array("character_playtime", $columns) && $table->integer("character_playtime")->nullable()->default("0");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("user_statistics");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `user_statistics`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `user_statistics` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}