<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePanelIpInfosTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("panel_ip_infos");

		$func = Schema::hasTable("panel_ip_infos") ? "table" : "create";

		Schema::$func("panel_ip_infos", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->bigInteger("id")->autoIncrement();
			!in_array("ip", $columns) && $table->string("ip", 255);
			!in_array("country", $columns) && $table->string("country", 255);
			!in_array("isp", $columns) && $table->string("isp", 255);
			!in_array("proxy", $columns) && $table->tinyInteger("proxy");
			!in_array("hosting", $columns) && $table->tinyInteger("hosting");
			!in_array("last_crawled", $columns) && $table->integer("last_crawled");
			!in_array("city", $columns) && $table->string("city", 255);
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("panel_ip_infos");
	}

	/**
	 * Collect all columns that are indexed in the panel_ip_infos table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("panel_ip_infos")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("panel_ip_infos");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}