<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateBlacklistedIdentifiersTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("blacklisted_identifiers");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("blacklisted_identifiers", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("blacklist_id", $columns) && $table->integer("blacklist_id")->autoIncrement();
			!in_array("identifier", $columns) && $table->string("identifier", 255)->nullable();
			!in_array("creator_identifier", $columns) && $table->longText("creator_identifier")->nullable();
			!in_array("reason", $columns) && $table->longText("reason")->nullable();
			!in_array("timestamp", $columns) && $table->timestamp("timestamp")->useCurrent();
			!in_array("note", $columns) && $table->longText("note")->nullable();

			!in_array("identifier", $indexes) && $table->index("identifier");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("blacklisted_identifiers");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `blacklisted_identifiers`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `blacklisted_identifiers` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}