<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateImportExportOrdersTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("import_export_orders");

		$func = Schema::hasTable("import_export_orders") ? "table" : "create";

		Schema::$func("import_export_orders", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("character_id", $columns) && $table->integer("character_id")->nullable();
			!in_array("company", $columns) && $table->string("company", 255)->nullable();
			!in_array("weight", $columns) && $table->integer("weight")->nullable();
			!in_array("items", $columns) && $table->longText("items")->nullable();
			!in_array("target_is_cayo", $columns) && $table->tinyInteger("target_is_cayo")->nullable()->default("0");
			!in_array("completed_at", $columns) && $table->integer("completed_at")->nullable();

			!in_array("id", $indexes) && $table->index("id");
			!in_array("character_id", $indexes) && $table->index("character_id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("import_export_orders");
	}

	/**
	 * Collect all columns that are indexed in the import_export_orders table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("import_export_orders")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("import_export_orders");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}