<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePanelLogsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("panel_logs");

		$func = Schema::hasTable("panel_logs") ? "table" : "create";

		Schema::$func("panel_logs", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->bigInteger("id")->autoIncrement();
			!in_array("source_identifier", $columns) && $table->string("source_identifier", 255);
			!in_array("target_identifier", $columns) && $table->string("target_identifier", 255);
			!in_array("timestamp", $columns) && $table->timestamp("timestamp")->default("current_timestamp()");
			!in_array("log", $columns) && $table->longText("log");
			!in_array("action", $columns) && $table->string("action", 255);
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("panel_logs");
	}

	/**
	 * Collect all columns that are indexed in the panel_logs table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("panel_logs")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("panel_logs");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}