<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateWebpanelUsersTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("webpanel_users");

		$func = Schema::hasTable("webpanel_users") ? "table" : "create";

		Schema::$func("webpanel_users", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->bigInteger("id")->autoIncrement();
			!in_array("account_id", $columns) && $table->string("account_id", 255);
			!in_array("name", $columns) && $table->string("name", 255);
			!in_array("avatar", $columns) && $table->string("avatar", 255);
			!in_array("remember_token", $columns) && $table->string("remember_token", 100)->nullable();
			!in_array("created_at", $columns) && $table->timestamp("created_at")->nullable();
			!in_array("updated_at", $columns) && $table->timestamp("updated_at")->nullable();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("webpanel_users");
	}

	/**
	 * Collect all columns that are indexed in the webpanel_users table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("webpanel_users")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("webpanel_users");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}