<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateGcphoneCallsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("gcphone_calls");

		$func = Schema::hasTable("gcphone_calls") ? "table" : "create";

		Schema::$func("gcphone_calls", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("owner", $columns) && $table->string("owner", 10)->nullable();
			!in_array("num", $columns) && $table->string("num", 10)->nullable();
			!in_array("incoming", $columns) && $table->integer("incoming")->nullable();
			!in_array("time", $columns) && $table->timestamp("time")->default("current_timestamp()");
			!in_array("accepts", $columns) && $table->integer("accepts")->nullable();

			!in_array("owner", $indexes) && $table->index("owner");
			!in_array("id", $indexes) && $table->index("id");
			!in_array("time", $indexes) && $table->index("time");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("gcphone_calls");
	}

	/**
	 * Collect all columns that are indexed in the gcphone_calls table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("gcphone_calls")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("gcphone_calls");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}