<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTradingCardsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("trading_cards");

		$func = Schema::hasTable("trading_cards") ? "table" : "create";

		Schema::$func("trading_cards", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("card_id", $columns) && $table->integer("card_id")->autoIncrement();
			!in_array("title", $columns) && $table->longText("title")->nullable();
			!in_array("image_url", $columns) && $table->longText("image_url")->nullable();
			!in_array("drop_category", $columns) && $table->string("drop_category", 50)->nullable()->default("bronze");
			!in_array("pack_id", $columns) && $table->integer("pack_id")->nullable()->default("0");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("trading_cards");
	}

	/**
	 * Collect all columns that are indexed in the trading_cards table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("trading_cards")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("trading_cards");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}