<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTwitterTweetsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("twitter_tweets");

		$func = Schema::hasTable("twitter_tweets") ? "table" : "create";

		Schema::$func("twitter_tweets", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("authorId", $columns) && $table->integer("authorId")->nullable();
			!in_array("realUser", $columns) && $table->string("realUser", 50)->nullable();
			!in_array("message", $columns) && $table->text("message")->nullable();
			!in_array("time", $columns) && $table->timestamp("time")->default("current_timestamp()");
			!in_array("likes", $columns) && $table->integer("likes")->nullable()->default("0");
			!in_array("is_deleted", $columns) && $table->tinyInteger("is_deleted")->nullable()->default("0");

			!in_array("time", $indexes) && $table->index("time");
			!in_array("id", $indexes) && $table->index("id");
			!in_array("authorId", $indexes) && $table->index("authorId");
			!in_array("message", $indexes) && $table->index("message");
			!in_array("is_deleted", $indexes) && $table->index("is_deleted");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("twitter_tweets");
	}

	/**
	 * Collect all columns that are indexed in the twitter_tweets table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("twitter_tweets")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("twitter_tweets");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}