<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateBlackjackMoneyChangeTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("blackjack_money_change");

		$func = Schema::hasTable("blackjack_money_change") ? "table" : "create";

		Schema::$func("blackjack_money_change", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("date_identifier", $columns) && $table->string("date_identifier", 50)->nullable();
			!in_array("server_id", $columns) && $table->integer("server_id")->nullable();
			!in_array("money_taken", $columns) && $table->integer("money_taken")->nullable()->default("0");
			!in_array("money_given", $columns) && $table->integer("money_given")->nullable()->default("0");
			!in_array("money_change", $columns) && $table->integer("money_change")->nullable()->default("0");

			!in_array("date_identifier", $indexes) && $table->index("date_identifier");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("blackjack_money_change");
	}

	/**
	 * Collect all columns that are indexed in the blackjack_money_change table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("blackjack_money_change")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("blackjack_money_change");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}