<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePanelLogSearchesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("panel_log_searches");

		$func = Schema::hasTable("panel_log_searches") ? "table" : "create";

		Schema::$func("panel_log_searches", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->bigInteger("id")->autoIncrement();
			!in_array("action", $columns) && $table->string("action", 255)->nullable();
			!in_array("details", $columns) && $table->string("details", 255)->nullable();
			!in_array("license_identifier", $columns) && $table->string("license_identifier", 255);
			!in_array("timestamp", $columns) && $table->integer("timestamp");
			!in_array("identifier", $columns) && $table->string("identifier", 255)->nullable();
			!in_array("server", $columns) && $table->string("server", 255)->nullable();
			!in_array("page", $columns) && $table->integer("page")->nullable();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("panel_log_searches");
	}

	/**
	 * Collect all columns that are indexed in the panel_log_searches table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("panel_log_searches")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("panel_log_searches");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}