<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSavingsAccountsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("savings_accounts");

		$func = Schema::hasTable("savings_accounts") ? "table" : "create";

		Schema::$func("savings_accounts", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("character_id", $columns) && $table->integer("character_id");
			!in_array("name", $columns) && $table->string("name", 255)->nullable();
			!in_array("balance", $columns) && $table->integer("balance")->nullable();
			!in_array("access", $columns) && $table->longText("access")->nullable();

			!in_array("id", $indexes) && $table->index("id");
			!in_array("character_id", $indexes) && $table->index("character_id");
			!in_array("access", $indexes) && $table->index("access");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("savings_accounts");
	}

	/**
	 * Collect all columns that are indexed in the savings_accounts table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("savings_accounts")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("savings_accounts");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}