<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateStocksOwnedSharesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("stocks_owned_shares");

		$func = Schema::hasTable("stocks_owned_shares") ? "table" : "create";

		Schema::$func("stocks_owned_shares", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("cid", $columns) && $table->integer("cid")->nullable();
			!in_array("company_id", $columns) && $table->integer("company_id")->nullable();
			!in_array("share_amount", $columns) && $table->integer("share_amount")->nullable();

			!in_array("cid", $indexes) && $table->index("cid");
			!in_array("company_id", $indexes) && $table->index("company_id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("stocks_owned_shares");
	}

	/**
	 * Collect all columns that are indexed in the stocks_owned_shares table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("stocks_owned_shares")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("stocks_owned_shares");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}