<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePhonesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("phones");

		$func = Schema::hasTable("phones") ? "table" : "create";

		Schema::$func("phones", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("phone_id", $columns) && $table->integer("phone_id")->autoIncrement();
			!in_array("sim_card_id", $columns) && $table->string("sim_card_id", 50)->nullable();
			!in_array("phone_passcode", $columns) && $table->longText("phone_passcode")->nullable();

			!in_array("phone_id", $indexes) && $table->index("phone_id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("phones");
	}

	/**
	 * Collect all columns that are indexed in the phones table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("phones")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("phones");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}