<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSpyDevicesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("spy_devices");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("spy_devices", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("device_id", $columns) && $table->integer("device_id")->autoIncrement();
			!in_array("device_type", $columns) && $table->integer("device_type")->nullable();
			!in_array("device_activation_timestamp", $columns) && $table->integer("device_activation_timestamp")->nullable();
			!in_array("entity_type", $columns) && $table->integer("entity_type")->nullable();
			!in_array("entity_identifier", $columns) && $table->integer("entity_identifier")->nullable();
			!in_array("entity_vector3", $columns) && $table->longText("entity_vector3")->nullable();

			!in_array("device_id", $indexes) && $table->index("device_id");
			!in_array("entity_type", $indexes) && $table->index("entity_type");
			!in_array("entity_identifier", $indexes) && $table->index("entity_identifier");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("spy_devices");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `spy_devices`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `spy_devices` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}