<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateLuckyWheelVehiclesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("lucky_wheel_vehicles");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("lucky_wheel_vehicles", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("server_id", $columns) && $table->integer("server_id")->nullable();
			!in_array("model_name", $columns) && $table->string("model_name", 50)->nullable();
			!in_array("has_been_won", $columns) && $table->tinyInteger("has_been_won")->nullable()->default("0");
			!in_array("has_been_won_by", $columns) && $table->string("has_been_won_by", 50)->nullable();
			!in_array("has_been_won_timestamp", $columns) && $table->integer("has_been_won_timestamp")->nullable();

			!in_array("id", $indexes) && $table->index("id");
			!in_array("has_been_won", $indexes) && $table->index("has_been_won");
			!in_array("server_id", $indexes) && $table->index("server_id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("lucky_wheel_vehicles");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `lucky_wheel_vehicles`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `lucky_wheel_vehicles` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}