<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateLuckyWheelVehiclesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("lucky_wheel_vehicles");

		$func = Schema::hasTable("lucky_wheel_vehicles") ? "table" : "create";

		Schema::$func("lucky_wheel_vehicles", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("model_name", $columns) && $table->string("model_name", 50)->nullable();
			!in_array("has_been_won", $columns) && $table->tinyInteger("has_been_won")->nullable()->default("0");
			!in_array("has_been_won_by", $columns) && $table->string("has_been_won_by", 50)->nullable();
			!in_array("server_id", $columns) && $table->integer("server_id")->nullable();
			!in_array("has_been_won_timestamp", $columns) && $table->integer("has_been_won_timestamp")->nullable();

			!in_array("has_been_won", $indexes) && $table->index("has_been_won");
			!in_array("id", $indexes) && $table->index("id");
			!in_array("server_id", $indexes) && $table->index("server_id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("lucky_wheel_vehicles");
	}

	/**
	 * Collect all columns that are indexed in the lucky_wheel_vehicles table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("lucky_wheel_vehicles")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("lucky_wheel_vehicles");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}