<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePhoneSimCardsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("phone_sim_cards");

		$func = Schema::hasTable("phone_sim_cards") ? "table" : "create";

		Schema::$func("phone_sim_cards", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("sim_card_id", $columns) && $table->integer("sim_card_id")->autoIncrement();
			!in_array("phone_id", $columns) && $table->integer("phone_id")->nullable();
			!in_array("character_id", $columns) && $table->integer("character_id")->nullable();
			!in_array("phone_settings", $columns) && $table->longText("phone_settings")->nullable();

			!in_array("sim_card_id", $indexes) && $table->index("sim_card_id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("phone_sim_cards");
	}

	/**
	 * Collect all columns that are indexed in the phone_sim_cards table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("phone_sim_cards")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("phone_sim_cards");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}