<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateStocksCompanyBlocksTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("stocks_company_blocks");

		$func = Schema::hasTable("stocks_company_blocks") ? "table" : "create";

		Schema::$func("stocks_company_blocks", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("block_id", $columns) && $table->integer("block_id")->nullable();
			!in_array("company_id", $columns) && $table->integer("company_id")->nullable();
			!in_array("last_payment", $columns) && $table->integer("last_payment")->nullable();
			!in_array("next_payment", $columns) && $table->integer("next_payment")->nullable();
			!in_array("terminate", $columns) && $table->integer("terminate")->nullable();

			!in_array("company_id", $indexes) && $table->index("company_id");
			!in_array("next_payment", $indexes) && $table->index("next_payment");
			!in_array("terminate", $indexes) && $table->index("terminate");
			!in_array("block_id", $indexes) && $table->index("block_id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("stocks_company_blocks");
	}

	/**
	 * Collect all columns that are indexed in the stocks_company_blocks table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("stocks_company_blocks")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("stocks_company_blocks");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}