<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateGolfHitsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("golf_hits");

		$func = Schema::hasTable("golf_hits") ? "table" : "create";

		Schema::$func("golf_hits", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("steam_identifier", $columns) && $table->string("steam_identifier", 50)->nullable();
			!in_array("name", $columns) && $table->longText("name")->nullable();
			!in_array("distance", $columns) && $table->double("distance")->nullable()->default("0");
			!in_array("date", $columns) && $table->longText("date")->nullable();

			!in_array("steam_identifier", $indexes) && $table->index("steam_identifier");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("golf_hits");
	}

	/**
	 * Collect all columns that are indexed in the golf_hits table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("golf_hits")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("golf_hits");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}