<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateSpecialImportsRotationTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("special_imports_rotation");

		$func = Schema::hasTable("special_imports_rotation") ? "table" : "create";

		Schema::$func("special_imports_rotation", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("vehicle_id", $columns) && $table->integer("vehicle_id")->autoIncrement();
			!in_array("model_name", $columns) && $table->longText("model_name")->nullable();
			!in_array("rotation_day", $columns) && $table->integer("rotation_day")->nullable();
			!in_array("remaining_stock", $columns) && $table->integer("remaining_stock")->nullable()->default("0");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("special_imports_rotation");
	}

	/**
	 * Collect all columns that are indexed in the special_imports_rotation table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("special_imports_rotation")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("special_imports_rotation");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}