<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateWebpanelSessionsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("webpanel_sessions");

		$func = Schema::hasTable("webpanel_sessions") ? "table" : "create";

		Schema::$func("webpanel_sessions", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("key", $columns) && $table->string("key", 40)->primary();
			!in_array("data", $columns) && $table->text("data");
			!in_array("last_accessed", $columns) && $table->integer("last_accessed");
			!in_array("last_viewed", $columns) && $table->string("last_viewed", 255);
			!in_array("user_agent", $columns) && $table->string("user_agent", 255);
			!in_array("ip_address", $columns) && $table->string("ip_address", 255);

			!in_array("last_accessed", $indexes) && $table->index("last_accessed");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("webpanel_sessions");
	}

	/**
	 * Collect all columns that are indexed in the webpanel_sessions table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("webpanel_sessions")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("webpanel_sessions");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}