<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateStocksRecentHistoryTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("stocks_recent_history");

		$func = Schema::hasTable("stocks_recent_history") ? "table" : "create";

		Schema::$func("stocks_recent_history", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("company_id", $columns) && $table->integer("company_id")->nullable();
			!in_array("cid", $columns) && $table->integer("cid")->nullable();
			!in_array("name", $columns) && $table->longText("name")->nullable();
			!in_array("text", $columns) && $table->longText("text")->nullable();
			!in_array("paid_amount", $columns) && $table->integer("paid_amount")->nullable();
			!in_array("share_change", $columns) && $table->double("share_change")->nullable();
			!in_array("timestamp", $columns) && $table->timestamp("timestamp")->default("current_timestamp()");

			!in_array("company_id", $indexes) && $table->index("company_id");
			!in_array("id", $indexes) && $table->index("id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("stocks_recent_history");
	}

	/**
	 * Collect all columns that are indexed in the stocks_recent_history table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("stocks_recent_history")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("stocks_recent_history");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}