<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateStocksCompanyEmployeesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("stocks_company_employees");

		$func = Schema::hasTable("stocks_company_employees") ? "table" : "create";

		Schema::$func("stocks_company_employees", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("company_id", $columns) && $table->integer("company_id")->nullable();
			!in_array("employee_cid", $columns) && $table->integer("employee_cid")->nullable();
			!in_array("employee_name", $columns) && $table->longText("employee_name")->nullable();
			!in_array("position", $columns) && $table->longText("position")->nullable();
			!in_array("salary", $columns) && $table->integer("salary")->nullable()->default("0");

			!in_array("company_id", $indexes) && $table->index("company_id");
			!in_array("employee_cid", $indexes) && $table->index("employee_cid");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("stocks_company_employees");
	}

	/**
	 * Collect all columns that are indexed in the stocks_company_employees table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("stocks_company_employees")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("stocks_company_employees");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}