<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTwitterAccountsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("twitter_accounts");

		$func = Schema::hasTable("twitter_accounts") ? "table" : "create";

		Schema::$func("twitter_accounts", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("username", $columns) && $table->string("username", 50)->nullable()->default("0");
			!in_array("password", $columns) && $table->string("password", 50)->nullable()->default("0");
			!in_array("avatar_url", $columns) && $table->string("avatar_url", 255)->nullable();
			!in_array("creator_cid", $columns) && $table->integer("creator_cid")->nullable();
			!in_array("is_verified", $columns) && $table->tinyInteger("is_verified")->nullable()->default("0");

			!in_array("username", $indexes) && $table->index("username");
			!in_array("creator_cid", $indexes) && $table->index("creator_cid");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("twitter_accounts");
	}

	/**
	 * Collect all columns that are indexed in the twitter_accounts table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("twitter_accounts")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("twitter_accounts");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}