<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFurnitureTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("furniture");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("furniture", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("property_id", $columns) && $table->integer("property_id")->nullable();
			!in_array("hash", $columns) && $table->bigInteger("hash")->nullable();
			!in_array("coords", $columns) && $table->longText("coords")->nullable();
			!in_array("storage_id", $columns) && $table->integer("storage_id")->nullable();
			!in_array("storage_size", $columns) && $table->integer("storage_size")->nullable();
			!in_array("weed_growth", $columns) && $table->integer("weed_growth")->nullable();
			!in_array("weed_timestamp", $columns) && $table->integer("weed_timestamp")->nullable();

			!in_array("id", $indexes) && $table->index("id");
			!in_array("property_id", $indexes) && $table->index("property_id");
			!in_array("storage_id", $indexes) && $table->index("storage_id");
			!in_array("weed_timestamp", $indexes) && $table->index("weed_timestamp");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("furniture");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `furniture`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `furniture` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}