<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateGcphoneUsersContactsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("gcphone_users_contacts");

		$func = Schema::hasTable("gcphone_users_contacts") ? "table" : "create";

		Schema::$func("gcphone_users_contacts", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("identifier", $columns) && $table->string("identifier", 60)->nullable();
			!in_array("number", $columns) && $table->string("number", 10)->nullable();
			!in_array("display", $columns) && $table->string("display", 64)->nullable()->default("-1");
			!in_array("theme", $columns) && $table->string("theme", 8)->nullable();

			!in_array("identifier", $indexes) && $table->index("identifier");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("gcphone_users_contacts");
	}

	/**
	 * Collect all columns that are indexed in the gcphone_users_contacts table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("gcphone_users_contacts")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("gcphone_users_contacts");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}