<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCasinoLogsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("casino_logs");

		$func = Schema::hasTable("casino_logs") ? "table" : "create";

		Schema::$func("casino_logs", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("license_identifier", $columns) && $table->string("license_identifier", 50)->nullable();
			!in_array("character_id", $columns) && $table->integer("character_id")->nullable();
			!in_array("game", $columns) && $table->enum("game", ["blackjack", "tracks", "slots"])->nullable();
			!in_array("money_spent", $columns) && $table->integer("money_spent")->nullable()->default("0");
			!in_array("money_earned", $columns) && $table->integer("money_earned")->nullable()->default("0");
			!in_array("details", $columns) && $table->longText("details")->nullable();
			!in_array("timestamp", $columns) && $table->timestamp("timestamp")->default("current_timestamp()");
			!in_array("money_won", $columns) && $table->integer("money_won")->nullable()->default("0");
			!in_array("bet_placed", $columns) && $table->integer("bet_placed")->nullable()->default("0");

			!in_array("license_identifier", $indexes) && $table->index("license_identifier");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("casino_logs");
	}

	/**
	 * Collect all columns that are indexed in the casino_logs table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("casino_logs")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("casino_logs");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}