<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateWarningsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("warnings");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("warnings", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("player_id", $columns) && $table->integer("player_id");
			!in_array("issuer_id", $columns) && $table->integer("issuer_id");
			!in_array("message", $columns) && $table->longText("message")->nullable();
			!in_array("created_at", $columns) && $table->timestamp("created_at")->useCurrent();
			!in_array("updated_at", $columns) && $table->timestamp("updated_at")->useCurrent();
			!in_array("warning_type", $columns) && $table->enum("warning_type", ["note", "warning", "strike", "system", "hidden"])->default("note");
			!in_array("can_be_deleted", $columns) && $table->tinyInteger("can_be_deleted")->default("1");

			!in_array("issuer_id", $indexes) && $table->index("issuer_id");
			!in_array("warning_type", $indexes) && $table->index("warning_type");
			!in_array("player_id", $indexes) && $table->index("player_id");
			!in_array("created_at", $indexes) && $table->index("created_at");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("warnings");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `warnings`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `warnings` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}