<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateLeaderboardBattleRoyaleTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("leaderboard_battle_royale");

		$func = Schema::hasTable("leaderboard_battle_royale") ? "table" : "create";

		Schema::$func("leaderboard_battle_royale", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("character_id", $columns) && $table->integer("character_id")->nullable();
			!in_array("kills", $columns) && $table->integer("kills")->nullable()->default("0");
			!in_array("deaths", $columns) && $table->integer("deaths")->nullable()->default("0");
			!in_array("hits", $columns) && $table->integer("hits")->nullable()->default("0");
			!in_array("hits_headshot", $columns) && $table->integer("hits_headshot")->nullable()->default("0");
			!in_array("damage_dealt", $columns) && $table->integer("damage_dealt")->nullable()->default("0");
			!in_array("damage_taken", $columns) && $table->integer("damage_taken")->nullable()->default("0");
			!in_array("wins", $columns) && $table->integer("wins")->nullable()->default("0");
			!in_array("matches", $columns) && $table->integer("matches")->nullable()->default("0");

			!in_array("character_id", $indexes) && $table->index("character_id");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("leaderboard_battle_royale");
	}

	/**
	 * Collect all columns that are indexed in the leaderboard_battle_royale table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("leaderboard_battle_royale")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("leaderboard_battle_royale");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}