<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePanelIpInfosTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("panel_ip_infos");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("panel_ip_infos", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->bigInteger("id")->autoIncrement();
			!in_array("ip", $columns) && $table->string("ip", 255);
			!in_array("country", $columns) && $table->string("country", 255);
			!in_array("isp", $columns) && $table->string("isp", 255);
			!in_array("proxy", $columns) && $table->tinyInteger("proxy");
			!in_array("hosting", $columns) && $table->tinyInteger("hosting");
			!in_array("last_crawled", $columns) && $table->integer("last_crawled");
			!in_array("city", $columns) && $table->string("city", 255);
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("panel_ip_infos");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `panel_ip_infos`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `panel_ip_infos` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}