<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateBlacklistedIdentifiersTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("blacklisted_identifiers");

		$func = Schema::hasTable("blacklisted_identifiers") ? "table" : "create";

		Schema::$func("blacklisted_identifiers", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("blacklist_id", $columns) && $table->integer("blacklist_id")->autoIncrement();
			!in_array("identifier", $columns) && $table->string("identifier", 255)->nullable();
			!in_array("creator_identifier", $columns) && $table->longText("creator_identifier")->nullable();
			!in_array("reason", $columns) && $table->longText("reason")->nullable();
			!in_array("timestamp", $columns) && $table->timestamp("timestamp")->default("current_timestamp()");
			!in_array("note", $columns) && $table->longText("note")->nullable();

			!in_array("identifier", $indexes) && $table->index("identifier");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("blacklisted_identifiers");
	}

	/**
	 * Collect all columns that are indexed in the blacklisted_identifiers table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("blacklisted_identifiers")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("blacklisted_identifiers");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}