<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateArcadeScoresTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("arcade_scores");

		$func = Schema::hasTable("arcade_scores") ? "table" : "create";

		Schema::$func("arcade_scores", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("score_id", $columns) && $table->integer("score_id")->autoIncrement();
			!in_array("character_id", $columns) && $table->integer("character_id")->nullable();
			!in_array("game_name", $columns) && $table->longText("game_name")->nullable();
			!in_array("score", $columns) && $table->integer("score")->nullable();

			!in_array("character_id", $indexes) && $table->index("character_id");
			!in_array("game_name", $indexes) && $table->index("game_name");
			!in_array("score", $indexes) && $table->index("score");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("arcade_scores");
	}

	/**
	 * Collect all columns that are indexed in the arcade_scores table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("arcade_scores")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("arcade_scores");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}