<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateDiscordEventsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$indexes = $this->collectIndexedColumns();
		$columns = Schema::getColumnListing("discord_events");

		$func = Schema::hasTable("discord_events") ? "table" : "create";

		Schema::$func("discord_events", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement();
			!in_array("name", $columns) && $table->longText("name")->nullable();
			!in_array("description", $columns) && $table->longText("description")->nullable();
			!in_array("location", $columns) && $table->longText("location")->nullable();
			!in_array("discord_event_id", $columns) && $table->string("discord_event_id", 255)->nullable();
			!in_array("timestamp_start", $columns) && $table->integer("timestamp_start")->nullable();
			!in_array("timestamp_end", $columns) && $table->integer("timestamp_end")->nullable();
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("discord_events");
	}

	/**
	 * Collect all columns that are indexed in the discord_events table.
	 *
	 * @return array
	 */
	private function collectIndexedColumns(): array
	{
		if (!Schema::hasTable("discord_events")) {
			return [];
		}

		$sm  = Schema::getConnection()->getDoctrineSchemaManager();
		$tbl = $sm->introspectTable("discord_events");

		$indexes = array_reduce($tbl->getIndexes(), function ($carry, $index) {
			return array_merge($carry, $index->getColumns());
		}, []);

		return array_values(array_unique($indexes));
	}
}