<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateStocksCompanyPropertiesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("stocks_company_properties");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("stocks_company_properties", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement(); // primary key
			!in_array("company_id", $columns) && $table->integer("company_id")->nullable();
			!in_array("block_id", $columns) && $table->integer("block_id")->nullable();
			!in_array("property_id", $columns) && $table->integer("property_id")->nullable();
			!in_array("property_name", $columns) && $table->string("property_name", 120)->nullable();
			!in_array("property_type", $columns) && $table->tinyInteger("property_type")->nullable();
			!in_array("property_address", $columns) && $table->string("property_address", 120)->nullable();
			!in_array("property_cost", $columns) && $table->integer("property_cost")->nullable();
			!in_array("property_renter", $columns) && $table->string("property_renter", 255)->nullable();
			!in_array("property_renter_cid", $columns) && $table->integer("property_renter_cid")->nullable();
			!in_array("property_income", $columns) && $table->integer("property_income")->nullable();
			!in_array("property_last_pay", $columns) && $table->integer("property_last_pay")->nullable();
			!in_array("shared_keys", $columns) && $table->longText("shared_keys")->nullable();
			!in_array("furniture_enabled", $columns) && $table->tinyInteger("furniture_enabled")->nullable()->default("1");
			!in_array("furniture_last_pay", $columns) && $table->integer("furniture_last_pay")->nullable();
			!in_array("terminate", $columns) && $table->integer("terminate")->nullable();

			!in_array("company_id", $indexes) && $table->index("company_id");
			!in_array("block_id", $indexes) && $table->index("block_id");
			!in_array("property_id", $indexes) && $table->index("property_id");
			!in_array("property_renter", $indexes) && $table->index("property_renter");
			!in_array("property_renter_cid", $indexes) && $table->index("property_renter_cid");
			!in_array("property_last_pay", $indexes) && $table->index("property_last_pay");
			!in_array("shared_keys", $indexes) && $table->index("shared_keys");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("stocks_company_properties");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `stocks_company_properties`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `stocks_company_properties` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}