<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateMediaDeviceBansTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("media_device_bans");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("media_device_bans", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("ban_id", $columns) && $table->integer("ban_id")->autoIncrement(); // primary key
			!in_array("media_devices", $columns) && $table->longText("media_devices")->nullable();
			!in_array("reason", $columns) && $table->longText("reason")->nullable();
			!in_array("note", $columns) && $table->longText("note")->nullable();
			!in_array("random_delay", $columns) && $table->tinyInteger("random_delay")->nullable()->default("0");
			!in_array("created_at", $columns) && $table->integer("created_at")->nullable()->default("0");

			!in_array("media_devices", $indexes) && $table->index("media_devices");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("media_device_bans");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `media_device_bans`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `media_device_bans` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}