<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateEconomyStatisticsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("economy_statistics");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("economy_statistics", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("date", $columns) && $table->string("date", 50)->primary(); // primary key
			!in_array("cash", $columns) && $table->bigInteger("cash")->nullable()->default("0");
			!in_array("bank", $columns) && $table->bigInteger("bank")->nullable()->default("0");
			!in_array("savings", $columns) && $table->bigInteger("savings")->nullable()->default("0");
			!in_array("stocks", $columns) && $table->bigInteger("stocks")->nullable()->default("0");
			!in_array("shared", $columns) && $table->bigInteger("shared")->nullable()->default("0");
			!in_array("bonds", $columns) && $table->bigInteger("bonds")->nullable()->default("0");
			!in_array("poorest", $columns) && $table->integer("poorest")->nullable()->default("0");
			!in_array("richest", $columns) && $table->integer("richest")->nullable()->default("0");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("economy_statistics");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `economy_statistics`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `economy_statistics` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}