<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateStocksCompaniesTransactionsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("stocks_companies_transactions");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("stocks_companies_transactions", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("transaction_id", $columns) && $table->integer("transaction_id")->autoIncrement(); // primary key
			!in_array("company_id", $columns) && $table->integer("company_id");
			!in_array("character_id", $columns) && $table->integer("character_id")->nullable();
			!in_array("amount", $columns) && $table->integer("amount")->nullable();
			!in_array("reason", $columns) && $table->string("reason", 50)->nullable();
			!in_array("timestamp", $columns) && $table->timestamp("timestamp")->useCurrent();

			!in_array("company_id", $indexes) && $table->index("company_id");
			!in_array("character_id", $indexes) && $table->index("character_id");
			!in_array("timestamp", $indexes) && $table->index("timestamp");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("stocks_companies_transactions");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `stocks_companies_transactions`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `stocks_companies_transactions` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}