<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateOutfitsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("outfits");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("outfits", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement(); // primary key
			!in_array("character_id", $columns) && $table->integer("character_id")->nullable();
			!in_array("name", $columns) && $table->string("name", 120)->nullable();
			!in_array("ped_data", $columns) && $table->longText("ped_data")->nullable();
			!in_array("showcase_url", $columns) && $table->string("showcase_url", 255)->nullable();
			!in_array("showcase_updated_at", $columns) && $table->integer("showcase_updated_at")->nullable();
			!in_array("updated_at", $columns) && $table->integer("updated_at")->nullable();
			!in_array("last_used_at", $columns) && $table->integer("last_used_at")->nullable();

			!in_array("character_id", $indexes) && $table->index("character_id");
			!in_array("name", $indexes) && $table->index("name");
			!in_array("last_used_at", $indexes) && $table->index("last_used_at");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("outfits");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `outfits`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `outfits` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}