<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateMdtReportsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("mdt_reports");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("mdt_reports", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("report_id", $columns) && $table->integer("report_id")->autoIncrement(); // primary key
			!in_array("creator_cid", $columns) && $table->integer("creator_cid");
			!in_array("editor_cid", $columns) && $table->integer("editor_cid");
			!in_array("title", $columns) && $table->string("title", 255)->nullable();
			!in_array("body", $columns) && $table->longText("body")->nullable();
			!in_array("created_at", $columns) && $table->integer("created_at")->nullable()->default("0");
			!in_array("modified_at", $columns) && $table->integer("modified_at")->nullable()->default("0");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("mdt_reports");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `mdt_reports`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `mdt_reports` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}