<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateStocksCompanyEmployeesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("stocks_company_employees");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("stocks_company_employees", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement(); // primary key
			!in_array("company_id", $columns) && $table->integer("company_id")->nullable();
			!in_array("employee_cid", $columns) && $table->integer("employee_cid")->nullable();
			!in_array("employee_name", $columns) && $table->string("employee_name", 255)->nullable();
			!in_array("position", $columns) && $table->string("position", 120)->nullable();
			!in_array("salary", $columns) && $table->integer("salary")->nullable()->default("0");
			!in_array("permissions", $columns) && $table->integer("permissions")->nullable()->default("0");

			!in_array("company_id", $indexes) && $table->index("company_id");
			!in_array("employee_cid", $indexes) && $table->index("employee_cid");
			!in_array("permissions", $indexes) && $table->index("permissions");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("stocks_company_employees");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `stocks_company_employees`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `stocks_company_employees` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}