<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCharactersTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("characters");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("characters", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("character_id", $columns) && $table->integer("character_id")->autoIncrement(); // primary key
			!in_array("license_identifier", $columns) && $table->string("license_identifier", 50)->nullable();
			!in_array("character_slot", $columns) && $table->integer("character_slot")->nullable();
			!in_array("character_created", $columns) && $table->integer("character_created")->nullable()->default("0");
			!in_array("character_creation_timestamp", $columns) && $table->integer("character_creation_timestamp")->nullable();
			!in_array("character_deleted", $columns) && $table->integer("character_deleted")->nullable()->default("0");
			!in_array("character_deletion_timestamp", $columns) && $table->integer("character_deletion_timestamp")->nullable();
			!in_array("first_name", $columns) && $table->string("first_name", 255)->nullable();
			!in_array("last_name", $columns) && $table->string("last_name", 255)->nullable();
			!in_array("date_of_birth", $columns) && $table->string("date_of_birth", 50)->nullable();
			!in_array("gender", $columns) && $table->integer("gender")->nullable();
			!in_array("backstory", $columns) && $table->longText("backstory")->nullable();
			!in_array("cash", $columns) && $table->integer("cash")->nullable()->default("0");
			!in_array("bank", $columns) && $table->integer("bank")->nullable()->default("0");
			!in_array("blood_type", $columns) && $table->string("blood_type", 10)->nullable();
			!in_array("married_to", $columns) && $table->integer("married_to")->nullable();
			!in_array("coords", $columns) && $table->string("coords", 120)->nullable();
			!in_array("status_data", $columns) && $table->longText("status_data")->nullable();
			!in_array("character_data", $columns) && $table->longText("character_data")->nullable();
			!in_array("is_hardcore_dead", $columns) && $table->tinyInteger("is_hardcore_dead")->nullable()->default("0");
			!in_array("is_one_life", $columns) && $table->tinyInteger("is_one_life")->nullable()->default("0");
			!in_array("has_ever_been_loaded", $columns) && $table->tinyInteger("has_ever_been_loaded")->nullable()->default("0");
			!in_array("on_duty_time", $columns) && $table->longText("on_duty_time")->nullable();
			!in_array("last_spawn_time", $columns) && $table->integer("last_spawn_time")->nullable();
			!in_array("last_seen", $columns) && $table->integer("last_seen")->nullable();
			!in_array("character_creation_time", $columns) && $table->integer("character_creation_time")->nullable();
			!in_array("playtime", $columns) && $table->integer("playtime")->nullable()->default("0");
			!in_array("weekly_playtime", $columns) && $table->longText("weekly_playtime")->nullable();
			!in_array("mugshot_url", $columns) && $table->string("mugshot_url", 255)->nullable();
			!in_array("email_address", $columns) && $table->string("email_address", 120)->nullable();
			!in_array("email_password", $columns) && $table->string("email_password", 120)->nullable();
			!in_array("ped_model_hash", $columns) && $table->bigInteger("ped_model_hash")->nullable();
			!in_array("ped_model_data", $columns) && $table->longText("ped_model_data")->nullable();
			!in_array("job_name", $columns) && $table->string("job_name", 120)->nullable();
			!in_array("department_name", $columns) && $table->string("department_name", 120)->nullable();
			!in_array("position_name", $columns) && $table->string("position_name", 120)->nullable();
			!in_array("ammo_data", $columns) && $table->longText("ammo_data")->nullable();
			!in_array("tattoos_data", $columns) && $table->longText("tattoos_data")->nullable();
			!in_array("phone_number", $columns) && $table->string("phone_number", 20)->nullable();
			!in_array("is_dead", $columns) && $table->tinyInteger("is_dead")->nullable();
			!in_array("stocks_balance", $columns) && $table->double("stocks_balance")->nullable()->default("0");
			!in_array("jail", $columns) && $table->integer("jail")->nullable();
			!in_array("gcphone_config", $columns) && $table->longText("gcphone_config")->nullable();
			!in_array("apartment", $columns) && $table->string("apartment", 120)->nullable();

			!in_array("character_id", $indexes) && $table->index("character_id");
			!in_array("character_slot", $indexes) && $table->index("character_slot");
			!in_array("character_created", $indexes) && $table->index("character_created");
			!in_array("license_identifier", $indexes) && $table->index("license_identifier");
			!in_array("character_deleted", $indexes) && $table->index("character_deleted");
			!in_array("last_name", $indexes) && $table->index("last_name");
			!in_array("first_name", $indexes) && $table->index("first_name");
			!in_array("last_spawn_time", $indexes) && $table->index("last_spawn_time");
			!in_array("email_address", $indexes) && $table->index("email_address");
			!in_array("ped_model_hash", $indexes) && $table->index("ped_model_hash");
			!in_array("playtime", $indexes) && $table->index("playtime");
			!in_array("phone_number", $indexes) && $table->index("phone_number");
			!in_array("character_data", $indexes) && $table->index("character_data");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("characters");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `characters`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `characters` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}