<?php
// Auto generated by the build:migrations command

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateMoneyLogsTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		// Make enums work pre laravel 10
		Schema::getConnection()->getDoctrineConnection()->getDatabasePlatform()->registerDoctrineTypeMapping("enum", "string");

		$tableExists = Schema::hasTable("money_logs");

		$indexes = $tableExists ? $this->getIndexedColumns() : [];
		$columns = $tableExists ? $this->getColumns() : [];

		$func = $tableExists ? "table" : "create";

		Schema::$func("money_logs", function (Blueprint $table) use ($columns, $indexes) {
			!in_array("id", $columns) && $table->integer("id")->autoIncrement(); // primary key
			!in_array("type", $columns) && $table->string("type", 50);
			!in_array("license_identifier", $columns) && $table->string("license_identifier", 50);
			!in_array("character_id", $columns) && $table->integer("character_id");
			!in_array("amount", $columns) && $table->integer("amount");
			!in_array("balance_after", $columns) && $table->integer("balance_after");
			!in_array("details", $columns) && $table->string("details", 50)->nullable();
			!in_array("timestamp", $columns) && $table->timestamp("timestamp")->useCurrent();

			!in_array("license_identifier", $indexes) && $table->index("license_identifier");
			!in_array("character_id", $indexes) && $table->index("character_id");
			!in_array("type", $indexes) && $table->index("type");
			!in_array("timestamp", $indexes) && $table->index("timestamp");
			!in_array("details", $indexes) && $table->index("details");
		});
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists("money_logs");
	}

	/**
	 * Get all columns.
	 *
	 * @return array
	 */
	private function getColumns(): array
	{
		$columns = Schema::getConnection()->select("SHOW COLUMNS FROM `money_logs`");

		return array_map(function ($column) {
			return $column->Field;
		}, $columns);
	}

	/**
	 * Get all indexed columns.
	 *
	 * @return array
	 */
	private function getIndexedColumns(): array
	{
		$indexes = Schema::getConnection()->select("SHOW INDEXES FROM `money_logs` WHERE Key_name != 'PRIMARY'");

		return array_map(function ($index) {
			return $index->Column_name;
		}, $indexes);
	}
}